-- ============================================================
-- QUANTUM5G — Módulo NR-01 | Seed
-- Versão: 0.1 | Data: 2026-04-18
--
-- Insere:
--   • 10 dimensões NR-01/GRO (catálogo fixo)
--   • 80 questões padrão v1.0 (8 por dimensão, Likert 1-5)
--   • Biblioteca inicial de intervenções (30 itens — semente)
--
-- Idempotente: ON CONFLICT DO NOTHING.
-- ============================================================

-- ============================================================
-- 1. DIMENSÕES NR-01
-- ============================================================
INSERT INTO nr01_dimensions (code, ord, name, description, nr01_clause, weight) VALUES
  ('carga_trabalho',        1, 'Carga de trabalho e ritmo',
     'Volume, prazos, sobrecarga e ritmo imposto pelo trabalho.',
     'NR-01 1.5.3.2 + Anexo Guia MTE — fatores de demanda', 1.10),
  ('controle_autonomia',    2, 'Controle e autonomia',
     'Liberdade de decisão sobre como, quando e em que ritmo executar tarefas.',
     'NR-01 1.5.3.2 + Maslach: Control', 1.05),
  ('exigencias_emocionais', 3, 'Exigências emocionais',
     'Desgaste afetivo, contato com sofrimento, regulação emocional exigida.',
     'NR-01 1.5.3.2 + Guia MTE Anexo I item 5', 1.10),
  ('reconhecimento',        4, 'Reconhecimento e recompensa',
     'Valorização, feedback, justiça percebida em remuneração e desenvolvimento.',
     'NR-01 1.5.3.2 + Maslach: Reward', 1.00),
  ('relacoes_interpessoais',5, 'Relações interpessoais (clima)',
     'Cooperação, suporte de pares, conflitos e comunicação na equipe.',
     'NR-01 1.5.3.2 + Maslach: Community', 1.00),
  ('estabilidade_seguranca',6, 'Segurança e estabilidade',
     'Previsibilidade contratual, mudanças organizacionais, sensação de continuidade.',
     'NR-01 1.5.3.2 + ILO PRIMA-EF', 0.95),
  ('assedio_violencia',     7, 'Violência e assédio',
     'Assédio moral, sexual, discriminação, retaliação e violência psicológica.',
     'Lei 14.457/2022 + NR-01 1.5.3.2 — risco crítico', 1.30),
  ('organizacao_trabalho',  8, 'Organização do trabalho',
     'Clareza de processos, retrabalho, definição de papéis e responsabilidades.',
     'NR-01 1.5.3.2 + Maslach: Fairness', 1.00),
  ('lideranca_gestao',      9, 'Liderança e gestão',
     'Apoio do gestor, direcionamento, qualidade da supervisão e feedback técnico.',
     'NR-01 1.5.3.2 + Guia MTE Anexo I item 7', 1.10),
  ('saude_bem_estar',      10, 'Saúde e bem-estar percebidos',
     'Estado físico-mental geral, qualidade do sono, sintomas de desgaste.',
     'NR-01 1.5.3.2 + WHO HW Ind.', 1.05)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  nr01_clause = EXCLUDED.nr01_clause,
  weight = EXCLUDED.weight;


-- ============================================================
-- 2. QUESTÕES (instrumento v1.0 — 80 questões)
-- Convenção: maior valor (5) sempre = "mais saudável".
-- Quando o item é negativo no enunciado, marca-se reverse_scored = true
-- e o motor inverte (6 - v) antes de agregar.
-- ============================================================
INSERT INTO nr01_questions (dimension_code, ord, text, reverse_scored, instrument_version) VALUES
  -- CARGA DE TRABALHO
  ('carga_trabalho', 1, 'Tenho tempo suficiente para realizar minhas tarefas com a qualidade esperada.', false, 'v1.0'),
  ('carga_trabalho', 2, 'Frequentemente trabalho além do meu horário regular para dar conta das demandas.', true,  'v1.0'),
  ('carga_trabalho', 3, 'O ritmo de trabalho que me é exigido é sustentável.', false, 'v1.0'),
  ('carga_trabalho', 4, 'Sinto-me sobrecarregado(a) na maior parte do tempo.', true,  'v1.0'),
  ('carga_trabalho', 5, 'Os prazos que recebo são realistas em relação à complexidade das tarefas.', false, 'v1.0'),
  ('carga_trabalho', 6, 'Saio do trabalho com energia para minha vida pessoal.', false, 'v1.0'),
  ('carga_trabalho', 7, 'Preciso interromper pausas e refeições para dar conta da demanda.', true,  'v1.0'),
  ('carga_trabalho', 8, 'Existe um equilíbrio aceitável entre o que me pedem e o que consigo entregar.', false, 'v1.0'),
  -- CONTROLE / AUTONOMIA
  ('controle_autonomia', 1, 'Tenho liberdade para decidir como executar minhas tarefas.', false, 'v1.0'),
  ('controle_autonomia', 2, 'Posso influenciar decisões importantes sobre o meu trabalho.', false, 'v1.0'),
  ('controle_autonomia', 3, 'Sei claramente o que se espera de mim na minha função.', false, 'v1.0'),
  ('controle_autonomia', 4, 'Tenho autonomia para organizar a sequência das minhas atividades.', false, 'v1.0'),
  ('controle_autonomia', 5, 'Recebo informações suficientes para tomar boas decisões no meu trabalho.', false, 'v1.0'),
  ('controle_autonomia', 6, 'Sinto que sou apenas um(a) executor(a) de ordens, sem voz ativa.', true, 'v1.0'),
  ('controle_autonomia', 7, 'Posso opinar sobre mudanças que afetam minha rotina.', false, 'v1.0'),
  ('controle_autonomia', 8, 'Recebo feedback claro sobre o desempenho do meu trabalho.', false, 'v1.0'),
  -- EXIGÊNCIAS EMOCIONAIS
  ('exigencias_emocionais', 1, 'Meu trabalho me expõe a situações emocionalmente difíceis.', true,  'v1.0'),
  ('exigencias_emocionais', 2, 'Preciso esconder o que sinto para conseguir realizar meu trabalho.', true,  'v1.0'),
  ('exigencias_emocionais', 3, 'Saio do expediente emocionalmente esgotado(a) com frequência.', true,  'v1.0'),
  ('exigencias_emocionais', 4, 'Tenho apoio adequado para lidar com situações emocionalmente complexas.', false, 'v1.0'),
  ('exigencias_emocionais', 5, 'Consigo manter o equilíbrio emocional mesmo nos dias mais difíceis.', false, 'v1.0'),
  ('exigencias_emocionais', 6, 'Levo problemas do trabalho para casa em pensamentos recorrentes.', true,  'v1.0'),
  ('exigencias_emocionais', 7, 'Sinto-me preparado(a) para lidar com clientes/pessoas difíceis.', false, 'v1.0'),
  ('exigencias_emocionais', 8, 'Existe espaço seguro na empresa para falar sobre como me sinto.', false, 'v1.0'),
  -- RECONHECIMENTO
  ('reconhecimento', 1, 'Minha contribuição é reconhecida pela liderança.', false, 'v1.0'),
  ('reconhecimento', 2, 'Sinto que meu salário/benefícios são justos para o que entrego.', false, 'v1.0'),
  ('reconhecimento', 3, 'Recebo elogios e reconhecimento quando faço um bom trabalho.', false, 'v1.0'),
  ('reconhecimento', 4, 'Tenho oportunidades reais de crescimento na empresa.', false, 'v1.0'),
  ('reconhecimento', 5, 'O que entrego é mais valorizado do que como me esforço.', true, 'v1.0'),
  ('reconhecimento', 6, 'Critérios de promoção e desenvolvimento são claros e justos.', false, 'v1.0'),
  ('reconhecimento', 7, 'Sinto-me invisível para a alta liderança da empresa.', true, 'v1.0'),
  ('reconhecimento', 8, 'Sinto orgulho do trabalho que faço e ele é reconhecido por isso.', false, 'v1.0'),
  -- RELAÇÕES INTERPESSOAIS / CLIMA
  ('relacoes_interpessoais', 1, 'Posso contar com meus colegas de trabalho quando preciso.', false, 'v1.0'),
  ('relacoes_interpessoais', 2, 'O ambiente entre colegas é cooperativo, não competitivo destrutivo.', false, 'v1.0'),
  ('relacoes_interpessoais', 3, 'Existem conflitos não resolvidos que afetam o trabalho.', true, 'v1.0'),
  ('relacoes_interpessoais', 4, 'Sinto-me parte de um time, não isolado(a).', false, 'v1.0'),
  ('relacoes_interpessoais', 5, 'A comunicação entre áreas funciona bem.', false, 'v1.0'),
  ('relacoes_interpessoais', 6, 'Posso ser quem eu sou no trabalho sem medo de julgamento.', false, 'v1.0'),
  ('relacoes_interpessoais', 7, 'Existe fofoca e politicagem que prejudicam o ambiente.', true, 'v1.0'),
  ('relacoes_interpessoais', 8, 'O respeito entre colegas é uma prática real, não apenas discurso.', false, 'v1.0'),
  -- ESTABILIDADE / SEGURANÇA
  ('estabilidade_seguranca', 1, 'Tenho confiança de que continuarei trabalhando aqui no próximo ano.', false, 'v1.0'),
  ('estabilidade_seguranca', 2, 'Mudanças organizacionais são comunicadas com clareza e antecedência.', false, 'v1.0'),
  ('estabilidade_seguranca', 3, 'Vivo com preocupação constante de perder meu emprego.', true, 'v1.0'),
  ('estabilidade_seguranca', 4, 'A empresa cumpre o que promete em relação a contratos e condições.', false, 'v1.0'),
  ('estabilidade_seguranca', 5, 'Reestruturações recentes foram conduzidas de forma respeitosa.', false, 'v1.0'),
  ('estabilidade_seguranca', 6, 'Sinto que posso planejar minha vida pessoal contando com este trabalho.', false, 'v1.0'),
  ('estabilidade_seguranca', 7, 'Há transparência sobre o futuro da empresa e do meu setor.', false, 'v1.0'),
  ('estabilidade_seguranca', 8, 'O clima de instabilidade me tira o sono ou a concentração.', true, 'v1.0'),
  -- ASSÉDIO / VIOLÊNCIA
  ('assedio_violencia', 1, 'Já presenciei comportamentos abusivos por parte de líderes ou pares.', true, 'v1.0'),
  ('assedio_violencia', 2, 'Sinto-me seguro(a) para denunciar comportamentos inadequados.', false, 'v1.0'),
  ('assedio_violencia', 3, 'Existe canal de denúncia confiável e protegido contra retaliação.', false, 'v1.0'),
  ('assedio_violencia', 4, 'Já sofri humilhações ou desrespeito intencional no trabalho.', true, 'v1.0'),
  ('assedio_violencia', 5, 'O respeito a diferenças (gênero, raça, orientação) é uma prática real.', false, 'v1.0'),
  ('assedio_violencia', 6, 'Já recebi comentários ou avanços de natureza sexual indesejados.', true, 'v1.0'),
  ('assedio_violencia', 7, 'Quem denuncia é tratado com seriedade e proteção pela empresa.', false, 'v1.0'),
  ('assedio_violencia', 8, 'Conheço a política de prevenção a assédio da minha empresa.', false, 'v1.0'),
  -- ORGANIZAÇÃO DO TRABALHO
  ('organizacao_trabalho', 1, 'Os processos de trabalho são claros e bem definidos.', false, 'v1.0'),
  ('organizacao_trabalho', 2, 'Tenho que refazer trabalho com frequência por falhas de comunicação.', true, 'v1.0'),
  ('organizacao_trabalho', 3, 'Sei a quem recorrer para tirar dúvidas sobre meu trabalho.', false, 'v1.0'),
  ('organizacao_trabalho', 4, 'Tenho ferramentas e recursos suficientes para fazer meu trabalho.', false, 'v1.0'),
  ('organizacao_trabalho', 5, 'Mudanças de prioridade acontecem de forma desorganizada.', true, 'v1.0'),
  ('organizacao_trabalho', 6, 'Reuniões na empresa têm objetivo claro e produzem decisões.', false, 'v1.0'),
  ('organizacao_trabalho', 7, 'Existem regras claras sobre comunicação fora do horário de trabalho.', false, 'v1.0'),
  ('organizacao_trabalho', 8, 'Recebo informação suficiente para entender o impacto do meu trabalho.', false, 'v1.0'),
  -- LIDERANÇA / GESTÃO
  ('lideranca_gestao', 1, 'Meu líder direto me dá apoio quando preciso.', false, 'v1.0'),
  ('lideranca_gestao', 2, 'Confio nas decisões da minha liderança imediata.', false, 'v1.0'),
  ('lideranca_gestao', 3, 'Recebo direcionamento técnico claro do meu gestor.', false, 'v1.0'),
  ('lideranca_gestao', 4, 'Meu líder se importa com meu bem-estar pessoal e profissional.', false, 'v1.0'),
  ('lideranca_gestao', 5, 'Meu líder reconhece quando erra e ajusta o curso.', false, 'v1.0'),
  ('lideranca_gestao', 6, 'A relação com meu líder é uma fonte de tensão.', true, 'v1.0'),
  ('lideranca_gestao', 7, 'Meu líder distribui as tarefas de forma justa entre o time.', false, 'v1.0'),
  ('lideranca_gestao', 8, 'Posso falar abertamente sobre problemas com meu líder.', false, 'v1.0'),
  -- SAÚDE / BEM-ESTAR
  ('saude_bem_estar', 1, 'Tenho dormido bem nos últimos 30 dias.', false, 'v1.0'),
  ('saude_bem_estar', 2, 'Tenho energia suficiente para minhas atividades fora do trabalho.', false, 'v1.0'),
  ('saude_bem_estar', 3, 'Sinto sintomas físicos (dor de cabeça, gastrite, tensão) ligados ao trabalho.', true, 'v1.0'),
  ('saude_bem_estar', 4, 'Sinto-me ansioso(a) ou apreensivo(a) por causa do trabalho.', true, 'v1.0'),
  ('saude_bem_estar', 5, 'Consigo desligar da rotina profissional nos meus dias de folga.', false, 'v1.0'),
  ('saude_bem_estar', 6, 'Penso em pedir afastamento por razões de saúde mental.', true, 'v1.0'),
  ('saude_bem_estar', 7, 'No geral, classifico minha saúde mental atual como boa.', false, 'v1.0'),
  ('saude_bem_estar', 8, 'A empresa oferece recursos efetivos de cuidado em saúde mental.', false, 'v1.0')
ON CONFLICT (dimension_code, ord, instrument_version) DO NOTHING;


-- ============================================================
-- 3. BIBLIOTECA DE INTERVENÇÕES (semente — 30 itens)
-- ============================================================
INSERT INTO nr01_intervention_library
  (code, dimension_code, applicable_levels, company_size, title, description,
   rollout_steps, expected_impact_pct, typical_duration_days, cost_band, evidence_refs)
VALUES
  ('INT-CARGA-001','carga_trabalho', ARRAY['atencao','elevado','critico'],'qualquer',
    'Auditoria de dimensionamento de equipe',
    'Mapear demanda real x capacidade instalada por área e revisar dimensionamento.',
    '["Levantar volume de tarefas por área (4 semanas)","Comparar com FTE disponível","Reportar gaps","Plano de redistribuição ou contratação"]'::jsonb,
    12.0, 60, 'medio',
    '["EU-OSHA Working Time","ILO Work Organization Guide"]'::jsonb),
  ('INT-CARGA-002','carga_trabalho', ARRAY['elevado','critico'],'qualquer',
    'Política de priorização e regra do "não" institucional',
    'Implementar critérios públicos de priorização e protocolo de recusa controlada.',
    '["Workshop de matriz de impacto/esforço","Publicar regra de aceite/recusa","Treinar líderes","Revisar mensalmente"]'::jsonb,
    10.0, 30, 'baixo',
    '["Maslach: Workload","Heath et al. 2018"]'::jsonb),
  ('INT-CARGA-003','carga_trabalho', ARRAY['atencao','elevado'],'qualquer',
    'Direito à desconexão formal',
    'Política escrita restringindo comunicações fora do horário de trabalho.',
    '["Redigir política","Aprovar com jurídico","Treinar liderança","Comunicar geral","Auditar mensalmente"]'::jsonb,
    8.0, 21, 'baixo',
    '["Lei francesa 2016","TST jurisprudência"]'::jsonb),

  ('INT-CONTROLE-001','controle_autonomia', ARRAY['atencao','elevado','critico'],'qualquer',
    'Redesenho de papéis com matriz RACI',
    'Redefinir responsabilidades por processo crítico para reduzir ambiguidade.',
    '["Mapear processos críticos","Workshop RACI","Validar com áreas","Publicar e treinar"]'::jsonb,
    11.0, 45, 'medio',
    '["PMI PMBOK","Maslach: Control"]'::jsonb),
  ('INT-CONTROLE-002','controle_autonomia', ARRAY['atencao','elevado'],'qualquer',
    'Ritmo de feedback estruturado (1:1 quinzenal)',
    'Implantar 1:1 quinzenais entre líder e liderado com pauta padronizada.',
    '["Treinar líderes em 1:1","Definir pauta mínima","Garantir agenda","Revisar adesão trimestralmente"]'::jsonb,
    9.0, 30, 'baixo',
    '["Gallup State of the Workplace","Buckingham 2019"]'::jsonb),

  ('INT-EMOCIONAL-001','exigencias_emocionais', ARRAY['elevado','critico'],'qualquer',
    'Programa de apoio psicológico (PAE/EAP)',
    'Convênio com EAP externo de teleterapia e atendimento confidencial.',
    '["RFP a 3 fornecedores","Negociar pacote por colaborador","Comunicar amplamente","Acompanhar utilização anonimizada"]'::jsonb,
    15.0, 45, 'medio',
    '["AETNA EAP study","WHO Mental Health at Work 2022"]'::jsonb),
  ('INT-EMOCIONAL-002','exigencias_emocionais', ARRAY['atencao','elevado'],'qualquer',
    'Treinamento de regulação emocional para áreas de contato com cliente',
    'Capacitar áreas expostas a clientes difíceis em técnicas de regulação.',
    '["Selecionar áreas críticas","Contratar facilitador","2 encontros de 4h","Avaliar 90 dias depois"]'::jsonb,
    10.0, 60, 'baixo',
    '["Grandey 2000 Emotional Labor"]'::jsonb),

  ('INT-RECONHECIMENTO-001','reconhecimento', ARRAY['atencao','elevado','critico'],'qualquer',
    'Programa de reconhecimento não-financeiro estruturado',
    'Sistema de reconhecimento entre pares e por liderança com critérios claros.',
    '["Definir critérios objetivos","Plataforma de kudos","Cerimônia mensal","Tornar visível ao C-level"]'::jsonb,
    10.0, 30, 'baixo',
    '["Gallup Q12: recognition","Maslach: Reward"]'::jsonb),
  ('INT-RECONHECIMENTO-002','reconhecimento', ARRAY['elevado','critico'],'media',
    'Revisão de equidade salarial por papel/perfil',
    'Análise estatística de equidade salarial por gênero, raça, tempo de casa.',
    '["Coletar base anonimizada","Análise estatística","Plano de ajustes 12-24 meses","Comunicação responsável"]'::jsonb,
    12.0, 90, 'alto',
    '["Lei 14.611/2023","Mercer Pay Equity Toolkit"]'::jsonb),

  ('INT-CLIMA-001','relacoes_interpessoais', ARRAY['atencao','elevado'],'qualquer',
    'Workshop de comunicação não-violenta para times críticos',
    'Capacitar times com baixo clima em CNV e gestão de conflitos.',
    '["Mapear times críticos","Contratar facilitador","2 dias intensivos","Acompanhamento mensal por 3 meses"]'::jsonb,
    9.0, 90, 'medio',
    '["Rosenberg CNV","Lencioni Five Dysfunctions"]'::jsonb),
  ('INT-CLIMA-002','relacoes_interpessoais', ARRAY['elevado','critico'],'qualquer',
    'Mediação formal de conflitos',
    'Processo estruturado de mediação para conflitos identificados.',
    '["Identificar conflitos via diagnóstico","Contratar mediador","Sessões de mediação","Acordos escritos"]'::jsonb,
    14.0, 45, 'medio',
    '["Harvard Negotiation Project","CFP guidelines"]'::jsonb),

  ('INT-ESTABILIDADE-001','estabilidade_seguranca', ARRAY['atencao','elevado','critico'],'qualquer',
    'Comunicação cadenciada sobre futuro da empresa',
    'Ritmo trimestral de all-hands com transparência sobre estado e direção.',
    '["Definir pauta mínima","All-hands trimestral","Q&A anônimo","Métricas compartilhadas"]'::jsonb,
    8.0, 90, 'baixo',
    '["Edelman Trust Barometer"]'::jsonb),
  ('INT-ESTABILIDADE-002','estabilidade_seguranca', ARRAY['elevado','critico'],'qualquer',
    'Protocolo de mudança organizacional respeitosa',
    'Padrão de comunicação e suporte para reestruturações.',
    '["Definir protocolo","Treinar HRBPs","Aplicar em próxima mudança","Auditar cumprimento"]'::jsonb,
    10.0, 30, 'baixo',
    '["Kotter 8-Step","Prosci ADKAR"]'::jsonb),

  ('INT-ASSEDIO-001','assedio_violencia', ARRAY['atencao','elevado','critico'],'qualquer',
    'Canal externo de denúncias com proteção',
    'Implantar canal de denúncias terceirizado com proteção contra retaliação.',
    '["RFP a 3 fornecedores","Política anti-retaliação","Treinamento universal","Auditoria semestral"]'::jsonb,
    18.0, 45, 'medio',
    '["Lei 14.457/2022 — CIPA+ assédio","ICC Whistleblowing Standard"]'::jsonb),
  ('INT-ASSEDIO-002','assedio_violencia', ARRAY['elevado','critico'],'qualquer',
    'Treinamento obrigatório anti-assédio com certificação',
    'Treinamento universal certificado conforme Lei 14.457/2022.',
    '["Adquirir conteúdo certificado","Trilha obrigatória 100% colaboradores","Reciclagem anual","Registro auditável"]'::jsonb,
    12.0, 60, 'baixo',
    '["Lei 14.457/2022","TST tese vinculante"]'::jsonb),
  ('INT-ASSEDIO-003','assedio_violencia', ARRAY['critico'],'qualquer',
    'Apuração formal e auditoria independente',
    'Investigação independente em caso de denúncias graves identificadas.',
    '["Contratar empresa externa","Investigação confidencial","Relatório com recomendações","Aplicar consequências"]'::jsonb,
    20.0, 60, 'alto',
    '["FBI Workplace Violence","CFP Boas Práticas Investigação"]'::jsonb),

  ('INT-ORG-001','organizacao_trabalho', ARRAY['atencao','elevado'],'qualquer',
    'Mapeamento e simplificação de processos críticos',
    'Identificar e eliminar retrabalho em 5 processos mais sensíveis.',
    '["Top 5 processos por queixa","Mapeamento BPMN","Workshop de simplificação","Implantar e medir"]'::jsonb,
    11.0, 90, 'medio',
    '["Lean Six Sigma","Womack Lean Thinking"]'::jsonb),
  ('INT-ORG-002','organizacao_trabalho', ARRAY['atencao','elevado','critico'],'qualquer',
    'Política de gestão de reuniões',
    'Reduzir reuniões improdutivas com regras claras e blocos de foco.',
    '["Auditar reuniões 30 dias","Política de pauta + ata","Bloqueios de foco semanais","Revisão trimestral"]'::jsonb,
    7.0, 30, 'baixo',
    '["Microsoft Work Trend Index","Asana Anatomy of Work"]'::jsonb),

  ('INT-LIDERANCA-001','lideranca_gestao', ARRAY['atencao','elevado','critico'],'qualquer',
    'Programa de desenvolvimento de líderes (6 encontros)',
    'Trilha de formação em gestão humana para todos os líderes.',
    '["Diagnóstico inicial 360","6 encontros mensais","Mentoria","Reaval. 12 meses"]'::jsonb,
    14.0, 180, 'alto',
    '["Gallup CliftonStrengths","Goleman Primal Leadership"]'::jsonb),
  ('INT-LIDERANCA-002','lideranca_gestao', ARRAY['atencao','elevado'],'qualquer',
    'Feedback 360° trimestral para liderança',
    'Avaliação 360° estruturada para todos os líderes.',
    '["Definir formulário","Plataforma 360","Devolutivas individuais","PDIs por líder"]'::jsonb,
    10.0, 90, 'medio',
    '["Korn Ferry Leadership","Drucker On Leadership"]'::jsonb),
  ('INT-LIDERANCA-003','lideranca_gestao', ARRAY['elevado','critico'],'qualquer',
    'Coaching individual para líderes em risco',
    'Coaching para líderes com avaliação 360 baixa ou queixas formais.',
    '["Identificar pelo diagnóstico","Contratar coach certificado","12 sessões","Reavaliar"]'::jsonb,
    16.0, 180, 'alto',
    '["ICF Coaching Standards","Whitmore Performance Coaching"]'::jsonb),

  ('INT-SAUDE-001','saude_bem_estar', ARRAY['atencao','elevado','critico'],'qualquer',
    'Telemedicina e telepsicologia 24x7',
    'Acesso ilimitado a atendimento clínico e psicológico para colaboradores.',
    '["Cotação com 3 fornecedores","Cobertura 100%","Comunicar uso confidencial","Acompanhar utilização anonimizada"]'::jsonb,
    13.0, 45, 'medio',
    '["WHO Telemedicine 2023","ANS RN-465"]'::jsonb),
  ('INT-SAUDE-002','saude_bem_estar', ARRAY['atencao','elevado'],'qualquer',
    'Pausa estruturada e ginástica laboral',
    'Programa de pausas obrigatórias e ginástica laboral diária.',
    '["Estruturar 3 pausas/dia","Contratar profissional Edu Física","Tornar obrigatório","Medir adesão"]'::jsonb,
    7.0, 30, 'baixo',
    '["NR-17 + ergonomia","SBME Ginástica Laboral"]'::jsonb),
  ('INT-SAUDE-003','saude_bem_estar', ARRAY['elevado','critico'],'media',
    'Núcleo de saúde mental ocupacional',
    'Equipe interna multidisciplinar de saúde mental ocupacional.',
    '["Contratar psicólogo + assistente social","Atendimento agendado","Articulação com PAE","Reportar indicadores"]'::jsonb,
    18.0, 90, 'alto',
    '["WHO Mental Health at Work","Min. da Saúde RAPS"]'::jsonb),

  ('INT-MULTI-001','carga_trabalho', ARRAY['critico'],'qualquer',
    'Comitê de gestão de risco psicossocial',
    'Comitê multidisciplinar (RH, SST, jurídico, líderes) para casos críticos.',
    '["Composição formal","Reunião mensal","Casos prioritários","Reportar ao CEO"]'::jsonb,
    9.0, 30, 'baixo',
    '["NR-01 1.5.5 — Comissão"]'::jsonb),
  ('INT-MULTI-002','organizacao_trabalho', ARRAY['atencao','elevado'],'qualquer',
    'Onboarding estruturado de 90 dias',
    'Programa formal de integração com checkpoints aos 30/60/90 dias.',
    '["Trilha de conteúdo","Buddy designado","Checkpoints com líder","Survey ao final"]'::jsonb,
    8.0, 90, 'baixo',
    '["Bauer Onboarding 2010","SHRM"]'::jsonb),
  ('INT-MULTI-003','reconhecimento', ARRAY['atencao','elevado'],'qualquer',
    'Stay interview com talentos-chave',
    'Entrevistas estruturadas com talentos identificados para retenção.',
    '["Mapear talentos-chave","Roteiro de stay interview","Realização semestral","Plano por pessoa"]'::jsonb,
    11.0, 60, 'baixo',
    '["Finnegan Stay Interview","SHRM"]'::jsonb),
  ('INT-MULTI-004','controle_autonomia', ARRAY['atencao','elevado'],'qualquer',
    'Modelo de trabalho híbrido formalizado',
    'Política clara de hibridismo com regras objetivas e flexibilidade.',
    '["Definir política","Acordar com lideranças","Comunicação formal","Avaliar trimestralmente"]'::jsonb,
    9.0, 45, 'baixo',
    '["Microsoft Hybrid 2022","Bloom Stanford"]'::jsonb),
  ('INT-MULTI-005','exigencias_emocionais', ARRAY['atencao','elevado'],'qualquer',
    'Rodas de conversa sobre saúde mental',
    'Espaços facilitados de troca sobre saúde mental no trabalho.',
    '["Calendário trimestral","Facilitador externo","Tema rotativo","Comunicação contínua"]'::jsonb,
    7.0, 90, 'baixo',
    '["Janeiro Branco","CFP Boas Práticas"]'::jsonb),
  ('INT-MULTI-006','saude_bem_estar', ARRAY['elevado','critico'],'qualquer',
    'Acompanhamento pós-afastamento (RTW)',
    'Protocolo de retorno ao trabalho após afastamento por CID F.',
    '["Protocolo Return-to-Work","Médico do trabalho + psicólogo","Plano gradual","Acompanhamento 6 meses"]'::jsonb,
    16.0, 180, 'medio',
    '["EU-OSHA RTW Guide","NIOSH"]'::jsonb)
ON CONFLICT (code) DO NOTHING;
