-- ============================================================
-- QUANTUM5G — Patch 008b: Seed dos 55 laudos canônicos v1.1
-- Versão: 0.8.0 | Data: 2026-04-20
-- Gerado por: scripts/_extract_laudos_v1.1.mjs
--
-- Fonte literal: docs/audit/NR01_GRO.md (= NR01_GRO.docx)
-- Total: 50 laudos micro + 5 laudos macro
-- Hash SHA-256 do conjunto: 424c9b15296acb64a6947691ceb0d53f4dfa61e434beb94ea98c203dd32b25a1
-- ============================================================

BEGIN;

INSERT INTO nr01_laudo_textos
  (dimension_code, nivel_risco, texto_principal, texto_recomendacao, instrument_version, is_active)
VALUES
  ('carga_trabalho', 'muito_baixo', E'A dimensão “Carga de Trabalho e Pressão” foi classificada como risco muito baixo, indicando que o volume de demandas, o ritmo de trabalho e as exigências operacionais encontram-se compatíveis com a capacidade de resposta da equipe. O fluxo de atividades tende a se organizar de forma funcional, permitindo que os colaboradores realizem suas tarefas com estabilidade, sem sinais relevantes de sobrecarga ou pressão excessiva.', E'Esse cenário favorece não apenas a execução adequada do trabalho, mas também a preservação do equilíbrio interno dos colaboradores diante das exigências do ambiente. Recomenda-se a manutenção das práticas atuais, com monitoramento periódico, a fim de garantir que o equilíbrio identificado se sustente frente a possíveis variações na demanda.', 'v1.1', true),
  ('carga_trabalho', 'baixo', E'A dimensão “Carga de Trabalho e Pressão” foi classificada como risco baixo, indicando a presença de sinais leves de aumento na demanda ou pressão operacional, ainda sem comprometimento significativo do funcionamento geral da equipe. Observa-se que, embora o ambiente permaneça funcional, existem momentos pontuais de maior exigência que podem gerar desconforto ou esforço adicional por parte dos colaboradores.', E'Esse nível de risco sugere atenção à dinâmica de distribuição de tarefas e à gestão de prazos, evitando que pequenos desalinhamentos evoluam para quadros de sobrecarga mais estruturados. Recomenda-se acompanhamento contínuo e ajustes finos na organização do trabalho, preservando o equilíbrio atualmente existente.', 'v1.1', true),
  ('carga_trabalho', 'atencao', E'A dimensão “Carga de Trabalho e Pressão” foi classificada em nível de atenção, indicando que o volume de demandas e a pressão por resultados começam a exercer influência perceptível sobre o ambiente de trabalho. Nesse cenário, o ritmo operacional tende a se intensificar, exigindo maior esforço dos colaboradores para dar conta das atividades, o que pode gerar desgaste progressivo.', E'Essa condição já apresenta potencial de impacto sobre a qualidade das entregas, a organização do trabalho e a estabilidade emocional da equipe. Recomenda-se a adoção de medidas preventivas, com revisão da distribuição de tarefas, priorização de demandas e alinhamento mais claro de expectativas, evitando a evolução para níveis mais críticos de risco.', 'v1.1', true),
  ('carga_trabalho', 'elevado', E'A dimensão “Carga de Trabalho e Pressão” foi classificada como risco elevado, evidenciando um cenário de sobrecarga significativa e pressão constante no ambiente organizacional. O volume de trabalho e o ritmo exigido tendem a ultrapassar a capacidade operacional da equipe, gerando esforço contínuo, sensação de urgência permanente e dificuldade de sustentação do desempenho ao longo do tempo.', E'Esse contexto impacta diretamente a qualidade do trabalho, aumenta a probabilidade de erros e favorece o desgaste dos colaboradores, tanto no plano funcional quanto no plano relacional. Recomenda-se intervenção estruturada, com reavaliação da carga de trabalho, redistribuição de atividades, revisão de prazos e possível adequação do dimensionamento da equipe.', 'v1.1', true),
  ('carga_trabalho', 'critico', E'A dimensão “Carga de Trabalho e Pressão” foi classificada como risco crítico, indicando comprometimento relevante da capacidade da equipe frente às exigências do trabalho. O nível de sobrecarga identificado tende a ser contínuo e intenso, gerando um ambiente marcado por pressão elevada, exaustão e perda progressiva de qualidade na execução das atividades.', E'Esse cenário representa risco direto ao funcionamento organizacional, podendo resultar em aumento de erros, queda acentuada de produtividade, desgaste acentuado dos colaboradores e maior probabilidade de afastamentos e rotatividade. Recomenda-se intervenção imediata, com revisão urgente da estrutura de trabalho, redistribuição das demandas, reorganização dos processos e análise do dimensionamento da equipe.', 'v1.1', true),
  ('controle_autonomia', 'muito_baixo', E'A dimensão “Controle e Autonomia sobre as Tarefas” foi classificada como risco muito baixo, indicando que os colaboradores percebem clareza em relação às suas funções, bem como liberdade adequada para organizar e executar suas atividades. O nível de autonomia encontra-se alinhado às responsabilidades atribuídas, favorecendo uma atuação segura, com tomada de decisão coerente e consistente no cotidiano de trabalho.', E'Esse cenário contribui para um funcionamento mais fluido das atividades, reduzindo ruídos operacionais e fortalecendo o senso de responsabilidade individual diante das demandas. Recomenda-se a manutenção das práticas atuais, com monitoramento contínuo, a fim de preservar o equilíbrio entre orientação institucional e autonomia operacional.', 'v1.1', true),
  ('controle_autonomia', 'baixo', E'A dimensão “Controle e Autonomia sobre as Tarefas” foi classificada como risco baixo, indicando a presença de pequenas limitações na autonomia ou na clareza de papéis, ainda sem impacto significativo no desempenho global da equipe. Observa-se que, em determinados momentos, podem ocorrer dúvidas quanto às responsabilidades ou restrições pontuais na tomada de decisão.', E'Embora o funcionamento geral se mantenha estável, esse cenário sugere a necessidade de ajustes finos na comunicação e na definição de atribuições, evitando ambiguidades que possam gerar insegurança operacional. Recomenda-se acompanhamento contínuo e reforço na clareza de papéis e expectativas.', 'v1.1', true),
  ('controle_autonomia', 'atencao', E'A dimensão “Controle e Autonomia sobre as Tarefas” foi classificada em nível de atenção, indicando que a limitação de autonomia ou a falta de clareza nas responsabilidades começa a impactar o desempenho e a organização do trabalho. Os colaboradores podem apresentar dificuldade na condução de suas atividades, com maior dependência de validações e insegurança na tomada de decisão.', E'Esse cenário tende a gerar lentidão nos processos, aumento de retrabalho e elevação da tensão no ambiente, uma vez que o fluxo de trabalho deixa de se sustentar de forma autônoma. Recomenda-se a adoção de medidas preventivas, com revisão das atribuições, alinhamento de responsabilidades e fortalecimento da comunicação entre liderança e equipe.', 'v1.1', true),
  ('controle_autonomia', 'elevado', E'A dimensão “Controle e Autonomia sobre as Tarefas” foi classificada como risco elevado, evidenciando um cenário de limitação significativa na autonomia dos colaboradores e/ou ausência de clareza quanto às responsabilidades e expectativas. Nesse contexto, observa-se dependência excessiva de direcionamento, insegurança na execução das atividades e dificuldade de sustentação das rotinas de trabalho.', E'Esse nível de risco compromete diretamente a eficiência operacional, favorece o acúmulo de demandas, aumenta a incidência de erros e impacta negativamente o clima organizacional. Recomenda-se intervenção estruturada, com redefinição clara de papéis, fortalecimento da autonomia responsável e alinhamento consistente entre liderança e equipe.', 'v1.1', true),
  ('controle_autonomia', 'critico', E'A dimensão “Controle e Autonomia sobre as Tarefas” foi classificada como risco crítico, indicando comprometimento relevante na capacidade dos colaboradores de compreender, organizar e executar suas atividades de forma funcional. A ausência de clareza e a limitação extrema de autonomia geram desorganização, insegurança constante e dependência excessiva da liderança.', E'Esse cenário tende a desestruturar o fluxo de trabalho, aumentar significativamente o retrabalho e comprometer o desempenho organizacional como um todo. Além disso, favorece desgaste contínuo e tensão no ambiente. Recomenda-se intervenção imediata, com reestruturação das funções, redefinição de responsabilidades e revisão do modelo de gestão adotado.', 'v1.1', true),
  ('exigencias_emocionais', 'muito_baixo', E'A dimensão “Exigências Emocionais e Equilíbrio Trabalho–Vida” foi classificada como risco muito baixo, indicando que as demandas emocionais do trabalho se mantêm em níveis compatíveis com a capacidade de regulação dos colaboradores. O ambiente permite que as pessoas lidem com as exigências cotidianas sem acúmulo significativo de tensão, preservando a continuidade do trabalho sem desgaste relevante.', E'Observa-se que há condições favoráveis para que o colaborador encerre sua jornada com adequada separação entre trabalho e vida pessoal, mantendo estabilidade emocional diante das demandas. Recomenda-se a manutenção das práticas atuais, com acompanhamento periódico, a fim de sustentar o equilíbrio identificado.', 'v1.1', true),
  ('exigencias_emocionais', 'baixo', E'A dimensão “Exigências Emocionais e Equilíbrio Trabalho–Vida” foi classificada como risco baixo, indicando a presença de demandas emocionais moderadas, ainda administráveis no cotidiano de trabalho. Em determinados momentos, pode haver aumento de tensão ou esforço emocional, porém sem comprometimento significativo da estabilidade geral da equipe.', E'Esse cenário sugere atenção à intensidade e à frequência das exigências emocionais, evitando que se tornem contínuas e cumulativas. Recomenda-se monitoramento e pequenos ajustes na dinâmica de trabalho, favorecendo espaços de reorganização e recuperação ao longo da jornada.', 'v1.1', true),
  ('exigencias_emocionais', 'atencao', E'A dimensão “Exigências Emocionais e Equilíbrio Trabalho–Vida” foi classificada em nível de atenção, indicando que as demandas emocionais do trabalho começam a gerar impacto perceptível sobre os colaboradores. Há sinais de desgaste, dificuldade de desligamento ao final da jornada e interferência do trabalho na vida pessoal.', E'Esse contexto pode afetar a qualidade das interações, a concentração e a continuidade das atividades, além de favorecer o acúmulo de tensão ao longo do tempo. Recomenda-se a adoção de medidas preventivas, com revisão das condições de trabalho, atenção à intensidade das demandas e estímulo a práticas que favoreçam o equilíbrio entre exigência e recuperação.', 'v1.1', true),
  ('exigencias_emocionais', 'elevado', E'A dimensão “Exigências Emocionais e Equilíbrio Trabalho–Vida” foi classificada como risco elevado, evidenciando um cenário de desgaste emocional significativo associado às atividades laborais. As demandas do trabalho passam a exigir esforço emocional contínuo, dificultando o equilíbrio interno dos colaboradores e a separação entre vida profissional e pessoal.', E'Esse nível de risco impacta diretamente o desempenho, a qualidade das relações e a estabilidade do ambiente, favorecendo tensão constante, irritabilidade e queda na capacidade de resposta frente às demandas. Recomenda-se intervenção estruturada, com revisão das exigências emocionais do trabalho, reorganização das atividades e fortalecimento das condições de suporte ao colaborador.', 'v1.1', true),
  ('exigencias_emocionais', 'critico', E'A dimensão “Exigências Emocionais e Equilíbrio Trabalho–Vida” foi classificada como risco crítico, indicando comprometimento relevante da capacidade dos colaboradores de lidar com as demandas emocionais do trabalho. O ambiente tende a gerar desgaste intenso e contínuo, com dificuldade significativa de recuperação ao longo do tempo.', E'Esse cenário representa risco direto à saúde dos colaboradores e ao funcionamento organizacional, podendo resultar em queda acentuada de desempenho, aumento de afastamentos e instabilidade nas relações de trabalho. Recomenda-se intervenção imediata, com revisão urgente das condições que geram exigência emocional elevada, reestruturação das rotinas e implementação de medidas de proteção ao bem-estar dos colaboradores.', 'v1.1', true),
  ('reconhecimento', 'muito_baixo', E'A dimensão “Reconhecimento e Recompensa” foi classificada como risco muito baixo, indicando que os colaboradores percebem valorização adequada pelo trabalho realizado, com reconhecimento coerente às entregas e esforços individuais. Há sinais de alinhamento entre desempenho e retorno recebido, o que favorece o engajamento e a continuidade das atividades com sentido e direção.', E'Esse cenário contribui para a sustentação da motivação, fortalecendo o vínculo entre colaborador e organização, além de reduzir tensões associadas à percepção de injustiça ou invisibilidade profissional. Recomenda-se a manutenção das práticas atuais, com monitoramento contínuo para preservação do equilíbrio identificado.', 'v1.1', true),
  ('reconhecimento', 'baixo', E'A dimensão “Reconhecimento e Recompensa” foi classificada como risco baixo, indicando a presença de pequenas lacunas na percepção de valorização profissional, ainda sem impacto significativo no funcionamento da equipe. Em alguns momentos, pode haver sensação pontual de falta de reconhecimento ou ausência de retorno mais estruturado sobre o desempenho.', E'Embora o cenário se mantenha funcional, esse nível de risco sugere atenção à consistência das práticas de feedback e valorização, evitando que percepções de invisibilidade se tornem recorrentes. Recomenda-se acompanhamento e ajustes na forma como o reconhecimento é comunicado e distribuído.', 'v1.1', true),
  ('reconhecimento', 'atencao', E'A dimensão “Reconhecimento e Recompensa” foi classificada em nível de atenção, indicando que a percepção de falta de valorização começa a impactar o ambiente de trabalho. Os colaboradores podem sentir que seus esforços não são devidamente reconhecidos, gerando desmotivação progressiva e redução do envolvimento com as atividades.', E'Esse cenário tende a afetar o comprometimento, a qualidade das entregas e a permanência dos profissionais na organização. Recomenda-se a adoção de medidas preventivas, com revisão das práticas de reconhecimento, fortalecimento do feedback e alinhamento mais claro entre desempenho e valorização.', 'v1.1', true),
  ('reconhecimento', 'elevado', E'A dimensão “Reconhecimento e Recompensa” foi classificada como risco elevado, evidenciando um cenário de percepção significativa de desvalorização profissional. Os colaboradores tendem a perceber ausência de reconhecimento proporcional ao esforço e ao desempenho, o que impacta diretamente a motivação, o engajamento e a relação com o trabalho.', E'Esse nível de risco favorece o distanciamento emocional em relação às atividades, aumento da insatisfação e possível elevação da rotatividade. Recomenda-se intervenção estruturada, com revisão dos critérios de reconhecimento, implantação de práticas consistentes de feedback e reavaliação das formas de valorização profissional adotadas pela organização.', 'v1.1', true),
  ('reconhecimento', 'critico', E'A dimensão “Reconhecimento e Recompensa” foi classificada como risco crítico, indicando comprometimento relevante na percepção de valorização dentro da organização. O ambiente tende a ser marcado por sensação de injustiça, invisibilidade profissional e ausência de retorno sobre o desempenho, gerando ruptura no vínculo entre colaborador e trabalho.', E'Esse cenário impacta diretamente o funcionamento organizacional, podendo resultar em queda acentuada de engajamento, aumento da rotatividade e deterioração do clima interno. Recomenda-se intervenção imediata, com revisão profunda das práticas de reconhecimento, estruturação de critérios claros de valorização e reposicionamento da gestão em relação ao desenvolvimento e retenção de pessoas.', 'v1.1', true),
  ('relacoes_interpessoais', 'muito_baixo', E'A dimensão “Relações Interpessoais e Clima Organizacional” foi classificada como risco muito baixo, indicando que as interações no ambiente de trabalho ocorrem de forma respeitosa, funcional e colaborativa. Observa-se um clima organizacional estável, no qual a comunicação flui com clareza e as diferenças são administradas sem gerar rupturas no cotidiano de trabalho.', E'Esse cenário favorece a construção de vínculos profissionais saudáveis, contribuindo para a continuidade das atividades com menor nível de tensão e maior cooperação entre os colaboradores. Recomenda-se a manutenção das práticas atuais, com acompanhamento contínuo, a fim de preservar a qualidade relacional e o equilíbrio do ambiente.', 'v1.1', true),
  ('relacoes_interpessoais', 'baixo', E'A dimensão “Relações Interpessoais e Clima Organizacional” foi classificada como risco baixo, indicando a presença de pequenas tensões ou dificuldades pontuais nas interações entre os colaboradores, ainda sem impacto significativo no funcionamento geral da equipe. Eventuais ruídos de comunicação ou divergências podem ocorrer, mas tendem a ser administrados sem comprometer a dinâmica de trabalho.', E'Esse cenário sugere atenção à qualidade das relações e à clareza na comunicação, evitando que pequenos desalinhamentos se tornem recorrentes. Recomenda-se acompanhamento contínuo e fortalecimento das práticas de diálogo e cooperação no ambiente.', 'v1.1', true),
  ('relacoes_interpessoais', 'atencao', E'A dimensão “Relações Interpessoais e Clima Organizacional” foi classificada em nível de atenção, indicando que as dificuldades nas interações começam a impactar o ambiente de trabalho. Há sinais de comunicação ineficaz, conflitos mais frequentes ou redução da colaboração entre os membros da equipe.', E'Esse contexto pode gerar aumento de tensão, dificultar o fluxo das atividades e comprometer a qualidade das relações profissionais. Recomenda-se a adoção de medidas preventivas, com foco na melhoria da comunicação, mediação de conflitos e fortalecimento do senso de equipe.', 'v1.1', true),
  ('relacoes_interpessoais', 'elevado', E'A dimensão “Relações Interpessoais e Clima Organizacional” foi classificada como risco elevado, evidenciando um ambiente marcado por tensões frequentes, conflitos mal administrados e fragilidade nas relações entre os colaboradores. A comunicação tende a apresentar falhas significativas, dificultando o alinhamento das atividades e a cooperação no dia a dia.', E'Esse cenário impacta diretamente o desempenho da equipe, aumenta o desgaste emocional e favorece a deterioração do clima organizacional. Recomenda-se intervenção estruturada, com ações voltadas à mediação de conflitos, reestruturação da comunicação interna e fortalecimento das relações de trabalho.', 'v1.1', true),
  ('relacoes_interpessoais', 'critico', E'A dimensão “Relações Interpessoais e Clima Organizacional” foi classificada como risco crítico, indicando comprometimento relevante das relações no ambiente de trabalho. O contexto tende a ser marcado por conflitos recorrentes, ausência de cooperação, comunicação disfuncional e possível presença de comportamentos que fragilizam o respeito entre os colaboradores.', E'Esse cenário representa risco direto ao funcionamento organizacional, podendo gerar rupturas na equipe, queda acentuada de produtividade e aumento significativo de desgaste entre os profissionais. Recomenda-se intervenção imediata, com ações consistentes de reorganização das relações, redefinição de práticas de convivência e atuação direta da gestão na condução do ambiente.', 'v1.1', true),
  ('estabilidade_seguranca', 'muito_baixo', E'A dimensão “Segurança e Estabilidade” foi classificada como risco muito baixo, indicando que o ambiente organizacional apresenta condições consistentes de previsibilidade, clareza institucional e confiança por parte dos colaboradores. As decisões da organização tendem a ser compreendidas, os movimentos internos não geram instabilidade significativa e há percepção de continuidade nas relações de trabalho, o que favorece uma atuação mais segura e organizada no cotidiano.', E'Esse cenário contribui para a construção de um ambiente no qual o colaborador consegue se posicionar com maior tranquilidade diante das demandas, sem a presença de tensões associadas à incerteza ou ao receio de impactos inesperados em sua trajetória profissional. A estabilidade percebida sustenta o engajamento, a continuidade das atividades e a qualidade das relações de trabalho. Recomenda-se a manutenção das práticas atuais, com monitoramento contínuo, garantindo que a previsibilidade e a confiança institucional sejam preservadas ao longo do tempo.', 'v1.1', true),
  ('estabilidade_seguranca', 'baixo', E'A dimensão “Segurança e Estabilidade” foi classificada como risco baixo, indicando a presença de sinais leves de insegurança ou instabilidade, ainda sem comprometimento significativo do ambiente organizacional. Em determinados momentos, podem surgir dúvidas quanto à condução institucional, mudanças pouco claras ou percepções pontuais de incerteza, sem que isso, contudo, afete de forma estruturada o funcionamento da equipe.', E'Esse nível de risco sugere atenção à forma como as decisões são comunicadas e à consistência das práticas organizacionais, evitando que pequenos ruídos se ampliem e gerem interpretações de instabilidade. A manutenção de uma comunicação clara, alinhada e coerente tende a sustentar a confiança já existente. Recomenda-se acompanhamento contínuo, com ajustes pontuais na transparência e no fluxo de informações.', 'v1.1', true),
  ('estabilidade_seguranca', 'atencao', E'A dimensão “Segurança e Estabilidade” foi classificada em nível de atenção, indicando que a percepção de instabilidade começa a se tornar mais presente no ambiente de trabalho. Os colaboradores podem apresentar dúvidas frequentes quanto à condução da organização, insegurança em relação às decisões e dificuldade de antecipar movimentos institucionais, o que gera um estado de alerta constante no cotidiano.', E'Esse cenário tende a impactar a qualidade das entregas, a continuidade dos processos e a forma como os colaboradores se posicionam diante das demandas, favorecendo retração, cautela excessiva ou desalinhamentos operacionais. A insegurança percebida pode também afetar o vínculo com a organização, reduzindo o nível de comprometimento. Recomenda-se a adoção de medidas preventivas, com fortalecimento da comunicação institucional, maior clareza nas decisões e alinhamento mais consistente entre gestão e equipe.', 'v1.1', true),
  ('estabilidade_seguranca', 'elevado', E'A dimensão “Segurança e Estabilidade” foi classificada como risco elevado, evidenciando um ambiente no qual a percepção de instabilidade se apresenta de forma significativa e contínua. Os colaboradores tendem a vivenciar insegurança em relação à permanência, às decisões organizacionais e ao direcionamento da instituição, o que interfere diretamente na forma como executam suas atividades e se relacionam com o trabalho.', E'Esse contexto favorece um funcionamento marcado por cautela excessiva, retração nas iniciativas e dificuldade de sustentação do desempenho, além de aumentar a tensão no ambiente e fragilizar as relações profissionais. A instabilidade percebida pode impactar a retenção de talentos e comprometer a continuidade dos processos internos. Recomenda-se intervenção estruturada, com revisão das práticas de comunicação, fortalecimento da transparência institucional e alinhamento consistente das decisões organizacionais.', 'v1.1', true),
  ('estabilidade_seguranca', 'critico', E'A dimensão “Segurança e Estabilidade” foi classificada como risco crítico, indicando comprometimento relevante da percepção de confiança e previsibilidade no ambiente organizacional. O contexto tende a ser marcado por incerteza constante, ausência de clareza nas decisões e sensação de instabilidade que atravessa o cotidiano de trabalho, afetando diretamente o posicionamento dos colaboradores diante das demandas.', E'Esse cenário representa risco elevado ao funcionamento da organização, podendo gerar desorganização interna, aumento da rotatividade, queda significativa de desempenho e fragilização do vínculo entre colaborador e instituição. A percepção de instabilidade contínua favorece desgaste emocional, insegurança nas ações e ruptura progressiva da confiança organizacional. Recomenda-se intervenção imediata, com reestruturação das práticas de gestão, fortalecimento da comunicação institucional e definição clara de diretrizes que restabeleçam a previsibilidade e a segurança no ambiente de trabalho.', 'v1.1', true),
  ('assedio_violencia', 'muito_baixo', E'A dimensão “Violência e Assédio” foi classificada como risco muito baixo, indicando que o ambiente de trabalho apresenta relações pautadas no respeito, na integridade e na adequação das condutas interpessoais. Não há evidências relevantes de práticas que configurem desrespeito sistemático, abuso de poder ou comportamentos que exponham os colaboradores a situações constrangedoras ou humilhantes.', E'Esse cenário favorece a construção de um ambiente seguro do ponto de vista relacional, no qual os colaboradores tendem a se posicionar com maior tranquilidade, sem receio de exposição indevida ou retaliação. A ausência de sinais de violência psicológica ou assédio contribui diretamente para a estabilidade das relações e para a continuidade saudável das atividades. Recomenda-se a manutenção das práticas atuais, com monitoramento contínuo e reforço institucional de condutas baseadas no respeito e na ética.', 'v1.1', true),
  ('assedio_violencia', 'baixo', E'A dimensão “Violência e Assédio” foi classificada como risco baixo, indicando a presença de sinais pontuais de comportamentos inadequados, ainda sem caracterização de padrão recorrente ou impacto estruturado no ambiente organizacional. Podem ocorrer situações isoladas de comunicação inadequada, posturas mais rígidas ou interações que geram desconforto momentâneo entre os colaboradores.', E'Embora o ambiente, de modo geral, se mantenha funcional, esse nível de risco sugere atenção às dinâmicas relacionais, evitando que comportamentos pontuais evoluam para padrões mais frequentes ou naturalizados. Recomenda-se acompanhamento contínuo, com reforço das diretrizes institucionais de conduta e estímulo a práticas de respeito e diálogo no ambiente de trabalho.', 'v1.1', true),
  ('assedio_violencia', 'atencao', E'A dimensão “Violência e Assédio” foi classificada em nível de atenção, indicando que comportamentos inadequados começam a se manifestar com maior frequência ou intensidade no ambiente de trabalho. Há sinais de interações que podem gerar constrangimento, exposição indevida ou desconforto entre os colaboradores, ainda que nem sempre formalmente reconhecidas como situações de assédio.', E'Esse cenário tende a impactar a segurança psicológica dos colaboradores, reduzindo a liberdade de expressão, a confiança nas relações e a qualidade das interações no cotidiano. A ausência de tratamento adequado dessas situações pode favorecer sua ampliação e naturalização. Recomenda-se a adoção de medidas preventivas, com fortalecimento das políticas internas, orientação clara sobre condutas aceitáveis e atuação mais próxima da liderança na condução das relações.', 'v1.1', true),
  ('assedio_violencia', 'elevado', E'A dimensão “Violência e Assédio” foi classificada como risco elevado, evidenciando a presença consistente de comportamentos que fragilizam o respeito no ambiente de trabalho. Observa-se recorrência de situações que podem envolver exposição, constrangimento, comunicação agressiva ou uso inadequado de autoridade, afetando diretamente a qualidade das relações e o bem-estar dos colaboradores.', E'Esse nível de risco compromete a segurança psicológica da equipe, favorece o aumento de tensão no ambiente e impacta negativamente o desempenho e a continuidade das atividades. A permanência desse cenário pode contribuir para o adoecimento dos colaboradores e elevar o risco institucional. Recomenda-se intervenção estruturada, com revisão das práticas de gestão, implementação de canais seguros de escuta e atuação direta na mediação e condução das relações.', 'v1.1', true),
  ('assedio_violencia', 'critico', E'A dimensão “Violência e Assédio” foi classificada como risco crítico, indicando comprometimento relevante das relações no ambiente de trabalho, com evidências consistentes de práticas que podem configurar situações de assédio, abuso de poder ou desrespeito sistemático. O contexto tende a ser marcado por interações que geram constrangimento, insegurança e retração por parte dos colaboradores.', E'Esse cenário representa risco elevado não apenas ao funcionamento organizacional, mas também à integridade dos profissionais e à responsabilidade institucional, podendo resultar em afastamentos, aumento da rotatividade e implicações legais. A fragilização das relações tende a comprometer a continuidade das atividades e a confiança no ambiente de trabalho. Recomenda-se intervenção imediata, com apuração criteriosa das situações, fortalecimento das políticas institucionais, definição clara de condutas e atuação firme da gestão na reorganização do ambiente.', 'v1.1', true),
  ('organizacao_trabalho', 'muito_baixo', E'A dimensão “Organização do Trabalho” foi classificada como risco muito baixo, indicando que os processos, fluxos operacionais e a distribuição das atividades se apresentam de forma estruturada, coerente e funcional. Há clareza nas responsabilidades, definição adequada de tarefas e alinhamento entre demanda e capacidade operacional, favorecendo a continuidade do trabalho sem interrupções significativas ou retrabalho.', E'Esse cenário contribui para um ambiente mais estável e previsível, no qual o colaborador consegue se orientar com segurança diante das demandas, sem necessidade de ajustes constantes ou improvisações. A organização adequada do trabalho reduz o desgaste, melhora a eficiência e sustenta a qualidade das entregas. Recomenda-se a manutenção das práticas atuais, com monitoramento contínuo, garantindo a preservação da estrutura organizacional existente.', 'v1.1', true),
  ('organizacao_trabalho', 'baixo', E'A dimensão “Organização do Trabalho” foi classificada como risco baixo, indicando a presença de pequenas falhas ou desalinhamentos nos processos e na distribuição das atividades, ainda sem impacto significativo no funcionamento geral da equipe. Em determinados momentos, podem ocorrer retrabalhos pontuais, dúvidas operacionais ou necessidade de ajustes na condução das tarefas.', E'Embora o ambiente se mantenha funcional, esse nível de risco sugere atenção à consistência dos fluxos de trabalho e à clareza na definição de responsabilidades. Pequenas falhas, quando recorrentes, podem gerar desgaste progressivo e perda de eficiência. Recomenda-se acompanhamento contínuo, com ajustes pontuais na organização dos processos e na comunicação das rotinas.', 'v1.1', true),
  ('organizacao_trabalho', 'atencao', E'A dimensão “Organização do Trabalho” foi classificada em nível de atenção, indicando que falhas nos processos e na estrutura operacional começam a impactar o desempenho da equipe. Observa-se presença mais frequente de retrabalho, indefinição de responsabilidades, desalinhamento entre áreas e dificuldade na condução das atividades de forma contínua e organizada.', E'Esse cenário tende a gerar aumento de desgaste, perda de produtividade e dificuldade na sustentação das rotinas de trabalho, exigindo esforço adicional dos colaboradores para manter o funcionamento das atividades. A ausência de organização clara favorece a descontinuidade e a fragmentação dos processos. Recomenda-se a adoção de medidas preventivas, com revisão dos fluxos de trabalho, definição mais precisa de responsabilidades e melhoria na comunicação operacional.', 'v1.1', true),
  ('organizacao_trabalho', 'elevado', E'A dimensão “Organização do Trabalho” foi classificada como risco elevado, evidenciando um cenário de desorganização significativa nos processos internos e na distribuição das atividades. Há falhas recorrentes na definição de tarefas, ausência de clareza nas responsabilidades e dificuldade de alinhamento entre as áreas, o que compromete diretamente a eficiência operacional.', E'Esse nível de risco impacta de forma direta o desempenho da equipe, favorecendo retrabalho constante, acúmulo de demandas e aumento do desgaste dos colaboradores. A falta de organização estruturada exige esforço contínuo para manter as atividades em funcionamento, gerando instabilidade no ambiente. Recomenda-se intervenção estruturada, com revisão dos processos, reconfiguração das rotinas de trabalho e alinhamento claro das responsabilidades e fluxos operacionais.', 'v1.1', true),
  ('organizacao_trabalho', 'critico', E'A dimensão “Organização do Trabalho” foi classificada como risco crítico, indicando comprometimento relevante da estrutura operacional da organização. O ambiente tende a ser marcado por desorganização contínua, ausência de definição clara de processos, falhas na distribuição de tarefas e dificuldade generalizada na condução das atividades.', E'Esse cenário representa risco direto ao funcionamento da organização, podendo resultar em queda acentuada de produtividade, aumento significativo de erros, desgaste intenso da equipe e comprometimento da qualidade das entregas. A ausência de estrutura organizacional adequada fragiliza a continuidade das operações e impacta diretamente o clima interno. Recomenda-se intervenção imediata, com reestruturação completa dos processos, definição clara de responsabilidades e reorganização das rotinas de trabalho.', 'v1.1', true),
  ('lideranca_gestao', 'muito_baixo', E'A dimensão “Liderança e Gestão” foi classificada como risco muito baixo, indicando que a atuação da liderança se apresenta de forma consistente, clara e funcional no cotidiano organizacional. Observa-se alinhamento entre orientação e prática, com comunicação adequada das expectativas, condução equilibrada das demandas e presença de suporte efetivo à equipe na execução das atividades.', E'Esse cenário favorece um ambiente no qual os colaboradores conseguem se organizar com maior segurança, mantendo continuidade no trabalho e estabilidade nas relações. A liderança tende a sustentar o funcionamento da equipe sem gerar ruídos desnecessários, contribuindo para a qualidade do clima organizacional e para a fluidez dos processos. Recomenda-se a manutenção das práticas atuais, com acompanhamento contínuo, garantindo a preservação do padrão de gestão identificado.', 'v1.1', true),
  ('lideranca_gestao', 'baixo', E'A dimensão “Liderança e Gestão” foi classificada como risco baixo, indicando a presença de pequenas inconsistências na atuação da liderança, ainda sem impacto significativo no funcionamento geral da equipe. Em determinados momentos, podem ocorrer falhas pontuais de comunicação, orientação pouco clara ou dificuldades específicas na condução de demandas.', E'Embora o ambiente permaneça funcional, esse nível de risco sugere atenção à consistência das práticas de gestão, evitando que desalinhamentos pontuais se tornem recorrentes. A clareza na comunicação, o alinhamento de expectativas e a presença mais estruturada da liderança tendem a sustentar o equilíbrio já existente. Recomenda-se acompanhamento contínuo e ajustes pontuais na forma de condução da equipe.', 'v1.1', true),
  ('lideranca_gestao', 'atencao', E'A dimensão “Liderança e Gestão” foi classificada em nível de atenção, indicando que a forma de condução da equipe começa a impactar o ambiente de trabalho. Há sinais de dificuldade na comunicação das diretrizes, inconsistência na gestão das demandas ou ausência de suporte adequado aos colaboradores, o que pode gerar insegurança e desalinhamento no cotidiano.', E'Esse cenário tende a afetar a organização do trabalho, a qualidade das relações e o desempenho da equipe, uma vez que a liderança deixa de sustentar de forma consistente o funcionamento do ambiente. Os colaboradores podem apresentar maior dependência de direcionamento ou dificuldade de se posicionar diante das demandas. Recomenda-se a adoção de medidas preventivas, com fortalecimento das práticas de gestão, desenvolvimento da liderança e alinhamento mais claro das expectativas.', 'v1.1', true),
  ('lideranca_gestao', 'elevado', E'A dimensão “Liderança e Gestão” foi classificada como risco elevado, evidenciando um cenário no qual a atuação da liderança apresenta fragilidades significativas. Observa-se dificuldade consistente na comunicação, condução inadequada das demandas, ausência de suporte efetivo à equipe e possível geração de pressão desnecessária no ambiente de trabalho.', E'Esse nível de risco compromete diretamente o funcionamento organizacional, afetando a organização das atividades, o clima interno e a qualidade das relações. A liderança, nesse contexto, tende a não sustentar o ambiente, contribuindo para o aumento de tensão, insegurança e desgaste entre os colaboradores. Recomenda-se intervenção estruturada, com desenvolvimento das competências de liderança, revisão das práticas de gestão e alinhamento claro entre direção e equipe.', 'v1.1', true),
  ('lideranca_gestao', 'critico', E'A dimensão “Liderança e Gestão” foi classificada como risco crítico, indicando comprometimento relevante na forma como a equipe é conduzida. O ambiente tende a ser marcado por ausência de direcionamento claro, comunicação inadequada, tomada de decisão inconsistente e práticas de gestão que fragilizam o funcionamento organizacional.', E'Esse cenário impacta diretamente todas as demais dimensões do trabalho, podendo gerar desorganização generalizada, aumento de conflitos, queda acentuada de desempenho e ruptura progressiva das relações profissionais. A atuação da liderança, nesse nível, deixa de sustentar o ambiente e passa a contribuir para sua desestruturação. Recomenda-se intervenção imediata, com revisão profunda do modelo de gestão, desenvolvimento intensivo da liderança e redefinição das práticas de condução da equipe.', 'v1.1', true),
  ('saude_bem_estar', 'muito_baixo', E'A dimensão “Saúde e Bem-Estar Relacionados ao Trabalho” foi classificada como risco muito baixo, indicando que os colaboradores, de modo geral, não apresentam sinais relevantes de desgaste associados ao contexto laboral. Observa-se que o ambiente permite a sustentação das atividades sem impacto significativo na disposição física, no equilíbrio emocional ou na capacidade de recuperação após a jornada de trabalho.', E'Esse cenário sugere que as exigências do trabalho estão ajustadas à capacidade dos colaboradores, favorecendo um funcionamento contínuo, sem acúmulo expressivo de tensão ou comprometimento do bem-estar. A preservação da saúde no ambiente organizacional contribui diretamente para a estabilidade do desempenho, a qualidade das relações e a permanência dos profissionais. Recomenda-se a manutenção das práticas atuais, com monitoramento periódico, garantindo a continuidade das condições favoráveis identificadas.', 'v1.1', true),
  ('saude_bem_estar', 'baixo', E'A dimensão “Saúde e Bem-Estar Relacionados ao Trabalho” foi classificada como risco baixo, indicando a presença de sinais leves de desgaste associados às atividades laborais, ainda sem comprometimento significativo da saúde dos colaboradores. Em determinados momentos, podem ocorrer cansaço, tensão ou redução pontual da disposição, sem que isso se configure como um padrão contínuo.', E'Embora o ambiente permaneça funcional, esse nível de risco sugere atenção à intensidade e à frequência das demandas, evitando o acúmulo progressivo de desgaste. Pequenos sinais, quando não observados, tendem a se ampliar ao longo do tempo. Recomenda-se acompanhamento contínuo e ajustes pontuais nas condições de trabalho, favorecendo a recuperação e a manutenção do equilíbrio dos colaboradores.', 'v1.1', true),
  ('saude_bem_estar', 'atencao', E'A dimensão “Saúde e Bem-Estar Relacionados ao Trabalho” foi classificada em nível de atenção, indicando que os efeitos do trabalho começam a impactar de forma mais consistente o bem-estar dos colaboradores. Observam-se sinais de desgaste mais frequentes, como cansaço persistente, tensão emocional e dificuldade de recuperação ao longo da rotina de trabalho.', E'Esse cenário tende a afetar a qualidade das entregas, a continuidade das atividades e a forma como os colaboradores se relacionam com o trabalho, podendo gerar redução de engajamento e aumento da irritabilidade no ambiente. A permanência desse contexto favorece o acúmulo de desgaste e a progressão para quadros mais críticos. Recomenda-se a adoção de medidas preventivas, com revisão das condições de trabalho, atenção às exigências do ambiente e fortalecimento de práticas que favoreçam o equilíbrio e a recuperação.', 'v1.1', true),
  ('saude_bem_estar', 'elevado', E'A dimensão “Saúde e Bem-Estar Relacionados ao Trabalho” foi classificada como risco elevado, evidenciando um cenário de desgaste significativo associado às atividades laborais. Os colaboradores tendem a apresentar sinais consistentes de cansaço, tensão emocional e dificuldade de sustentação do desempenho ao longo do tempo, indicando impacto direto do ambiente de trabalho sobre sua condição de bem-estar.', E'Esse nível de risco compromete não apenas a qualidade das entregas, mas também a estabilidade das relações e a continuidade das atividades, favorecendo aumento de afastamentos, queda de produtividade e maior vulnerabilidade ao adoecimento. O ambiente, nesse contexto, deixa de sustentar o colaborador e passa a exigir além de sua capacidade de resposta. Recomenda-se intervenção estruturada, com revisão das condições de trabalho, reorganização das demandas e implementação de medidas voltadas à preservação da saúde dos colaboradores.', 'v1.1', true),
  ('saude_bem_estar', 'critico', E'A dimensão “Saúde e Bem-Estar Relacionados ao Trabalho” foi classificada como risco crítico, indicando comprometimento relevante da saúde dos colaboradores em decorrência das condições de trabalho. O ambiente tende a gerar desgaste intenso e contínuo, com sinais evidentes de exaustão, dificuldade de recuperação e impacto direto sobre o funcionamento físico e emocional dos profissionais.', E'Esse cenário representa risco elevado ao funcionamento organizacional, podendo resultar em aumento significativo de afastamentos, queda acentuada de desempenho, elevação da rotatividade e comprometimento da continuidade das atividades. A persistência desse contexto favorece o agravamento do quadro e amplia os riscos institucionais. Recomenda-se intervenção imediata, com revisão urgente das condições de trabalho, redução de fatores de desgaste e implementação de ações efetivas de proteção à saúde e ao bem-estar dos colaboradores.', 'v1.1', true)
ON CONFLICT (dimension_code, nivel_risco, instrument_version) DO UPDATE SET
  texto_principal    = EXCLUDED.texto_principal,
  texto_recomendacao = EXCLUDED.texto_recomendacao,
  is_active          = EXCLUDED.is_active;

INSERT INTO nr01_laudo_macros
  (nivel_risco, texto_principal, texto_recomendacao, instrument_version, is_active)
VALUES
  ('muito_baixo', E'O índice geral de risco psicossocial foi classificado como risco muito baixo, indicando que o ambiente organizacional, de forma global, apresenta condições favoráveis ao funcionamento do trabalho e à preservação da saúde dos colaboradores. As dimensões avaliadas demonstram alinhamento consistente entre demandas, estrutura organizacional e capacidade de resposta da equipe, sem evidência de fatores críticos que comprometam o equilíbrio do ambiente.', E'Esse cenário reflete um contexto no qual o trabalho se organiza de maneira funcional, permitindo continuidade nas atividades, estabilidade nas relações e sustentação do desempenho ao longo do tempo. A ausência de riscos relevantes sugere que a organização consegue operar sem gerar desgaste significativo ou impacto negativo sobre os colaboradores. Recomenda-se a manutenção das práticas atuais, com monitoramento periódico dos indicadores psicossociais, garantindo a preservação das condições identificadas.', 'v1.1', true),
  ('baixo', E'O índice geral de risco psicossocial foi classificado como risco baixo, indicando que o ambiente organizacional apresenta, de forma geral, condições adequadas de funcionamento, com presença de fatores pontuais que não comprometem significativamente a dinâmica do trabalho. As dimensões avaliadas demonstram estabilidade predominante, ainda que com pequenas fragilidades que podem gerar desconfortos localizados ou variações na experiência dos colaboradores.', E'Esse cenário sugere que o ambiente se mantém funcional e capaz de sustentar as atividades, porém requer atenção a aspectos específicos que, se negligenciados, podem evoluir para níveis mais elevados de risco. A organização apresenta base estrutural consistente, com necessidade de ajustes finos na condução de determinadas dimensões. Recomenda-se monitoramento contínuo e intervenções pontuais, visando a manutenção do equilíbrio identificado e a prevenção de agravamentos.', 'v1.1', true),
  ('atencao', E'O índice geral de risco psicossocial foi classificado em nível de atenção, indicando que o ambiente organizacional apresenta sinais consistentes de desgaste e desequilíbrio em diferentes dimensões do trabalho. As condições avaliadas revelam a presença de fatores que começam a impactar o funcionamento da equipe, a qualidade das relações e a continuidade das atividades, ainda que não de forma totalmente desestruturante.', E'Esse cenário aponta para um ambiente que mantém sua operação, porém com esforço crescente por parte dos colaboradores para sustentar o desempenho, o que tende a gerar acúmulo de tensão ao longo do tempo. A presença simultânea de fragilidades em múltiplas dimensões sugere risco de progressão para níveis mais elevados caso não haja intervenção. Recomenda-se a adoção de medidas preventivas estruturadas, com foco na reorganização das condições de trabalho e no fortalecimento dos fatores de proteção organizacional.', 'v1.1', true),
  ('elevado', E'O índice geral de risco psicossocial foi classificado como risco elevado, evidenciando que o ambiente organizacional apresenta comprometimento significativo em diferentes dimensões relacionadas ao trabalho. As condições identificadas indicam que os fatores de risco não estão isolados, mas se manifestam de forma integrada, impactando diretamente o desempenho, o clima organizacional e a estabilidade das relações profissionais.', E'Esse cenário tende a exigir esforço contínuo dos colaboradores para manter o funcionamento das atividades, gerando desgaste progressivo, aumento de tensão e redução da qualidade das entregas. A coexistência de múltiplos fatores de risco eleva a probabilidade de efeitos mais amplos, como queda de produtividade, aumento da rotatividade e comprometimento do bem-estar dos profissionais. Recomenda-se intervenção estruturada, com definição de plano de ação consistente, acompanhamento sistemático e reavaliação periódica dos indicadores.', 'v1.1', true),
  ('critico', E'O índice geral de risco psicossocial foi classificado como risco crítico, indicando comprometimento relevante do ambiente organizacional em múltiplas dimensões do trabalho. As condições avaliadas revelam um contexto no qual os fatores de risco se encontram intensificados e inter-relacionados, gerando impacto direto sobre o funcionamento da organização, a saúde dos colaboradores e a continuidade das atividades.', E'Esse cenário representa um nível elevado de vulnerabilidade institucional, caracterizado por desgaste acentuado, instabilidade nas relações, dificuldade de sustentação do desempenho e aumento significativo dos riscos ocupacionais. A persistência dessas condições tende a agravar o quadro, ampliando os efeitos sobre produtividade, clima e retenção de profissionais. Recomenda-se intervenção imediata, com revisão profunda das condições de trabalho, implementação de medidas corretivas urgentes e acompanhamento contínuo até estabilização do ambiente.', 'v1.1', true)
ON CONFLICT (nivel_risco, instrument_version) DO UPDATE SET
  texto_principal    = EXCLUDED.texto_principal,
  texto_recomendacao = EXCLUDED.texto_recomendacao,
  is_active          = EXCLUDED.is_active;

DO $$
DECLARE
  n_micros int;
  n_macros int;
  n_dims_micros int;
BEGIN
  SELECT COUNT(*) INTO n_micros
    FROM nr01_laudo_textos
   WHERE instrument_version = 'v1.1' AND is_active = true;

  SELECT COUNT(*) INTO n_macros
    FROM nr01_laudo_macros
   WHERE instrument_version = 'v1.1' AND is_active = true;

  SELECT COUNT(DISTINCT dimension_code) INTO n_dims_micros
    FROM nr01_laudo_textos
   WHERE instrument_version = 'v1.1' AND is_active = true;

  IF n_micros <> 50 THEN
    RAISE EXCEPTION 'Patch 008b: esperados 50 micros v1.1 ativos, encontrados %', n_micros;
  END IF;
  IF n_macros <> 5 THEN
    RAISE EXCEPTION 'Patch 008b: esperados 5 macros v1.1 ativos, encontrados %', n_macros;
  END IF;
  IF n_dims_micros <> 10 THEN
    RAISE EXCEPTION 'Patch 008b: esperadas 10 dimensões nos micros, encontradas %', n_dims_micros;
  END IF;

  RAISE NOTICE 'Patch 008b: OK (50 micros + 5 macros, 10 dimensões cobertas)';
END $$;

COMMIT;
